"""topic fix chart filed length

Revision ID: 19774ed00556
Revises: 47810986823c
Create Date: 2017-05-14 23:29:17.039930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19774ed00556'
down_revision = '47810986823c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('chart', sa.String(length=1024), nullable=True))
    op.create_unique_constraint(None, 'topics', ['chart'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_column('topics', 'chart')
    # ### end Alembic commands ###
