"""empty message

Revision ID: 2b70fb53b346
Revises: 84144c11a13d
Create Date: 2017-05-02 17:22:06.841051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b70fb53b346'
down_revision = '84144c11a13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimators', 'estimator',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimators', 'estimator',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
