"""fix models 4/9

Revision ID: 2d9a7963a598
Revises: 571bb547dae7
Create Date: 2017-04-09 22:17:03.428710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9a7963a598'
down_revision = '571bb547dae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datasets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'user_id')
    # ### end Alembic commands ###
