"""change performance to Text

Revision ID: 5f92b9b4614b
Revises: 828c15ce8b6b
Create Date: 2017-05-04 02:15:08.337427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f92b9b4614b'
down_revision = '828c15ce8b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimators', 'performance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('performance', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
