"""add topic table

Revision ID: 688062f46329
Revises: 83f09ee710ae
Create Date: 2017-05-12 13:41:12.885103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '688062f46329'
down_revision = '83f09ee710ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('estimators', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.drop_constraint('estimators_ibfk_2', 'estimators', type_='foreignkey')
    op.create_foreign_key(None, 'estimators', 'topics', ['topic_id'], ['id'])
    op.drop_column('estimators', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'estimators', type_='foreignkey')
    op.create_foreign_key('estimators_ibfk_2', 'estimators', 'users', ['user_id'], ['id'])
    op.drop_column('estimators', 'topic_id')
    op.drop_table('topics')
    # ### end Alembic commands ###
