"""remove estimator

Revision ID: 8186ee9f5a04
Revises: 2b70fb53b346
Create Date: 2017-05-04 02:11:44.685786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8186ee9f5a04'
down_revision = '2b70fb53b346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimators', 'estimator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('estimator', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
