"""change estimator to largeBinary

Revision ID: 828c15ce8b6b
Revises: 8186ee9f5a04
Create Date: 2017-05-04 02:12:12.617107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828c15ce8b6b'
down_revision = '8186ee9f5a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('estimator', sa.LargeBinary(length=65536), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimators', 'estimator')
    # ### end Alembic commands ###
