"""change performance to Text

Revision ID: 83f09ee710ae
Revises: 5f92b9b4614b
Create Date: 2017-05-04 02:15:42.086471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f09ee710ae'
down_revision = '5f92b9b4614b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('performance', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimators', 'performance')
    # ### end Alembic commands ###
