"""empty message

Revision ID: 84144c11a13d
Revises: dac0b92da6ed
Create Date: 2017-05-01 21:40:49.080368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84144c11a13d'
down_revision = 'dac0b92da6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('features_str', sa.Text(), nullable=True))
    op.add_column('estimators', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('estimators', sa.Column('performance', sa.String(length=64), nullable=True))
    op.add_column('estimators', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('estimators', 'text_features_str')
    op.drop_column('estimators', 'numerical_features_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('numerical_features_str', mysql.TEXT(), nullable=True))
    op.add_column('estimators', sa.Column('text_features_str', mysql.TEXT(), nullable=True))
    op.drop_column('estimators', 'status')
    op.drop_column('estimators', 'performance')
    op.drop_column('estimators', 'name')
    op.drop_column('estimators', 'features_str')
    # ### end Alembic commands ###
