"""topic add chart filed

Revision ID: addc83e6c855
Revises: 0db4d63e3ba7
Create Date: 2017-05-13 22:13:14.514075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addc83e6c855'
down_revision = '0db4d63e3ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('chart', sa.String(length=64), nullable=True))
    op.add_column('topics', sa.Column('chart_clfs', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'topics', ['name'])
    op.create_unique_constraint(None, 'topics', ['chart'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_column('topics', 'chart_clfs')
    op.drop_column('topics', 'chart')
    # ### end Alembic commands ###
