"""fix models_1

Revision ID: ead40fcd76c7
Revises: 2d9a7963a598
Create Date: 2017-04-09 22:20:53.783256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead40fcd76c7'
down_revision = '2d9a7963a598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimators', sa.Column('numerical_features_str', sa.Text(), nullable=True))
    op.add_column('estimators', sa.Column('text_features_str', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimators', 'text_features_str')
    op.drop_column('estimators', 'numerical_features_str')
    # ### end Alembic commands ###
