"""topic add timestamp

Revision ID: f563a661137b
Revises: 3f71198e49b7
Create Date: 2017-05-12 21:12:54.748985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f563a661137b'
down_revision = '3f71198e49b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_topics_timestamp'), 'topics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_timestamp'), table_name='topics')
    op.drop_column('topics', 'timestamp')
    # ### end Alembic commands ###
